import { ToastContainer} from 'react-toastify';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AuthProvider from "@/context/AuthProvider";

import { AuthContext } from "@/context/AuthContext";
import Loading from "@/components/shared/Loading";
import ClientLayout from "@/components/shared/ClientLayout";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Home | MegaMart",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {

  

  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-8xl mx-auto `}
      >
         <ToastContainer/>
        <AuthProvider>
        <ClientLayout>
            {children}
        </ClientLayout>
        
        </AuthProvider>

       


      </body>
    </html>
  );
}
